version: '3'

services:
  web_service:
    build: ./web_service
    volumes:
     - .:/web-semantic
    ports:
     - 1234:1234
    stdin_open: true
    tty: true

  simple_web_app:
    build: ./simple_web_app
    volumes:
     - .:/web-semantic
    ports:
     - 8080:8080
    stdin_open: true
    tty: true
